# Generated by Django 5.0.1 on 2024-02-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_added",
            field=models.DateField(auto_now_add=True),
        ),
    ]
