# Generated by Django 5.0.1 on 2024-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_order_order_date_alter_product_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.CharField(default="", max_length=255),
        ),
    ]
